# Generated by Django 3.1.5 on 2021-09-02 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='biograpy',
            new_name='biography',
        ),
    ]
